"""Tests for interface/gtp_wrapper.py, driving the GTP engine in-process through
Engine.send() so every reply can be checked.

Tests marked xfail pin the intended behavior of known bugs, to be decided and fixed
separately.
"""
import os

import gtp
import pytest

from AlphaGo import go
from AlphaGo.util import sgf_to_gamestate
from interface import gtp_wrapper
from interface.gtp_wrapper import ExtendedGtpEngine, GTPGameConnector, run_gtp
from tests import test_gamestate


class ScriptedPlayer(object):
    """Returns the given moves in order, recording whose turn each request was for."""

    def __init__(self, moves=()):
        self.moves = list(moves)
        self.asked_for = []
        self.own_moves = []

    def get_move(self, state, own_moves=None):
        self.asked_for.append(state.get_current_player())
        self.own_moves.append(own_moves)
        return self.moves.pop(0) if self.moves else go.PASS


def _engine(player=None):
    game = GTPGameConnector(player or ScriptedPlayer())
    return ExtendedGtpEngine(game, "Test Player", "1.2"), game


def _ok(response=None):
    return "= {}\n\n".format(response) if response is not None else "=\n\n"


def _err(message):
    return "? {}\n\n".format(message)


# --- identity / board setup ------------------------------------------------------------

def test_name_and_version():
    engine, _ = _engine()
    assert engine.send("name") == _ok("Test Player")
    assert engine.send("version") == _ok("1.2")


def test_message_ids_are_echoed():
    engine, _ = _engine()
    assert engine.send("7 name") == "=7 Test Player\n\n"


def test_boardsize_resizes_the_game():
    engine, game = _engine()
    assert engine.send("boardsize 9") == _ok()
    assert game._state.get_size() == 9


def test_clear_board_empties_the_game_and_keeps_its_size():
    engine, game = _engine()
    engine.send("boardsize 13")
    engine.send("play black D4")
    assert engine.send("clear_board") == _ok()
    assert game._state.get_history() == []
    assert game._state.get_size() == 13


def test_komi_is_recorded():
    engine, game = _engine()
    assert engine.send("komi 6.5") == _ok()
    assert game._komi == 6.5


@pytest.mark.parametrize("command", ["time_left B 60 0", "load_sgf x.sgf", "save_sgf x.sgf"])
def test_accepted_no_op_commands(command):
    engine, _ = _engine()
    assert engine.send(command) == _ok()


# --- play / genmove --------------------------------------------------------------------

def test_play_translates_vertex_and_color():
    engine, game = _engine()
    assert engine.send("play black D4") == _ok()   # D = 4th column (GTP skips I)
    assert engine.send("play white Q16") == _ok()
    board = game._state.get_board()
    # GTP rows count up from the bottom; the engine's y counts down from the top
    assert game._state.get_history() == [(3, 15), (15, 3)]
    assert board[3][15] == go.BLACK and board[15][3] == go.WHITE


def test_play_same_color_twice_uses_the_given_color():
    engine, game = _engine()
    engine.send("play black D4")
    engine.send("play black Q16")
    assert game._state.get_board()[15][3] == go.BLACK


# --- orientation: GTP counts rows from the bottom, SGF (and the engine) from the top ------

def test_gtp_game_is_oriented_like_its_sgf_record():
    """A position arriving over GTP matches the same game read from SGF, so the network
    sees KGS games exactly as it would see their downloaded records."""
    engine, game = _engine()
    engine.send("play black C3")
    engine.send("play white Q16")
    assert game._state.get_history() == sgf_to_gamestate(
        "(;GM[1]SZ[19];B[cq];W[pd])").get_history()


def test_sgf_sent_to_gnugo_uses_standard_coordinates():
    engine, game = _engine()
    engine.send("play black C3")
    engine.send("play white Q16")
    path = game.get_current_state_as_sgf()
    try:
        with open(path) as f:
            text = f.read()
    finally:
        os.remove(path)
    assert ";B[cq]" in text and ";W[pd]" in text


@pytest.mark.parametrize("size,vertex", [(19, "C3"), (19, "Q16"), (19, "T19"), (19, "A1"),
                                         (9, "C3"), (9, "J9"), (13, "N1")])
def test_vertex_round_trips_through_the_engine(size, vertex):
    """A move played at a vertex and then generated by the engine comes back as that same
    vertex - on any board size."""
    engine, game = _engine()
    engine.send("boardsize {}".format(size))
    engine.send("play black " + vertex)
    [played] = game._state.get_history()
    engine, _ = _engine(ScriptedPlayer([played]))
    engine.send("boardsize {}".format(size))
    assert engine.send("genmove black") == _ok(vertex)


def test_play_pass():
    engine, game = _engine()
    assert engine.send("play black pass") == _ok()
    assert game._state.get_history() == [None]
    assert game._state.get_current_player() == go.WHITE


def test_play_pass_out_of_turn_is_that_colors_pass():
    engine, game = _engine()
    assert engine.send("play white pass") == _ok()   # black to move, white passes
    assert game._state.get_current_player() == go.BLACK


def test_handicap_sent_as_consecutive_black_moves_keeps_real_colors():
    engine, game = _engine()
    for command in ["play black D4", "play black Q16", "play white Q4", "play white pass"]:
        assert engine.send(command) == _ok()
    assert [c for _m, c in game._state.get_history_with_colors()] == [
        go.BLACK, go.BLACK, go.WHITE, go.WHITE]
    assert game._state.get_current_player() == go.BLACK


# --- server moves are recorded leniently, the bot's own moves checked strictly ------------

def _gtp(point, size):
    """Engine (x, y) -> GTP vertex string."""
    x, y = point
    return "ABCDEFGHJKLMNOPQRST"[x] + str(size - y)


def _reach_superko_position(engine):
    """Play TestKo's non-alternating superko sequence over GTP on 9x9: White to move,
    and White retaking at engine (1, 1) - GTP B8 - would repeat an earlier position."""
    engine.send("boardsize 9")
    for move, color in test_gamestate.TestKo.NON_ALTERNATING_SUPERKO_MOVES:
        vertex = "pass" if move is None else _gtp(move, 9)
        name = "black" if color == go.BLACK else "white"
        assert engine.send("play {} {}".format(name, vertex)) == _ok()


def test_play_records_a_superko_repeat_the_server_allows():
    """Under KGS Japanese rules repeating a position is legal. The server's word goes: the
    engine must follow the real game even though its own positional superko forbids it."""
    engine, game = _engine()
    _reach_superko_position(engine)
    assert not game._state.is_legal((1, 1))
    assert engine.send("play white B8") == _ok()
    assert game._state.get_board()[1][1] == go.WHITE


def test_genmove_refuses_to_claim_a_move_the_engine_rejects():
    engine, game = _engine(ScriptedPlayer([(1, 1)]))  # a superko repeat - illegal for us
    _reach_superko_position(engine)
    history = game._state.get_history_with_colors()
    assert engine.send("genmove white") == _err("engine rejected its own move B8")
    assert game._state.get_history_with_colors() == history


def test_rejected_play_leaves_the_turn_unchanged():
    engine, game = _engine()
    engine.send("play black D4")
    assert engine.send("play black D4") == _err("illegal move")  # occupied, out of turn
    assert game._state.get_current_player() == go.WHITE


def test_play_rejects_suicide():
    engine, game = _engine()
    engine.send("play black B1")
    engine.send("play black A2")
    assert engine.send("play white A1") == _err("illegal move")  # no liberties, no capture
    assert len(game._state.get_history()) == 2


@pytest.mark.parametrize("move", ["black D4", "black T20", "black Z1", "purple D4", "black"])
def test_illegal_or_malformed_play_is_rejected(move):
    engine, _ = _engine()
    engine.send("play white D4")
    assert engine.send("play " + move) == _err("illegal move")


def test_genmove_asks_the_player_and_plays_its_move():
    player = ScriptedPlayer([(3, 3)])
    engine, game = _engine(player)
    assert engine.send("genmove white") == _ok("D16")  # engine y=3 is the 4th row from the top
    assert player.asked_for == [go.WHITE]
    assert game._state.get_board()[3][3] == go.WHITE


def test_genmove_pass():
    engine, game = _engine()
    assert engine.send("genmove b") == _ok("PASS")
    assert game._state.get_history() == [None]


def test_genmove_unknown_color():
    engine, _ = _engine()
    assert engine.send("genmove purple") == _err("unknown player: purple")


# --- handicap --------------------------------------------------------------------------

@pytest.mark.parametrize("stones", range(2, 10))
def test_place_free_handicap_uses_the_recommended_points(stones):
    engine, game = _engine()
    vertices = ExtendedGtpEngine.recommended_handicaps[stones]
    assert engine.send("place_free_handicap {}".format(stones)) == _ok(vertices)
    expected = [(x - 1, 19 - y) for x, y in map(gtp.parse_vertex, vertices.split())]
    assert game._state.get_handicaps() == expected
    assert game._state.get_current_player() == go.WHITE


@pytest.mark.parametrize("arg,message", [
    ("1", "Invalid number of handicap stones: 1"),
    ("10", "Invalid number of handicap stones: 10"),
    ("many", "Number of handicaps could not be parsed: many"),
])
def test_place_free_handicap_rejects_bad_counts(arg, message):
    engine, game = _engine()
    assert engine.send("place_free_handicap " + arg) == _err(message)
    assert game._state.get_history() == []


def test_set_free_handicap_places_the_given_stones():
    engine, game = _engine()
    assert engine.send("set_free_handicap C3 R17 K10") == _ok()
    assert game._state.get_handicaps() == [(2, 16), (16, 2), (9, 9)]


# --- scoring through gnugo -------------------------------------------------------------

def test_call_gnugo_without_gnugo_installed_returns_nothing(tmp_path):
    engine, _ = _engine()
    sgf = tmp_path / "g.sgf"
    sgf.write_text("(;GM[1]SZ[19])")
    assert engine.call_gnugo(str(sgf), "final_score\n") == ""


@pytest.mark.parametrize("command,gnugo_command", [
    ("final_score", "final_score\n"),
    ("final_status_list dead", "final_status_list dead\n"),
])
def test_scoring_commands_send_the_game_to_gnugo(monkeypatch, command, gnugo_command):
    engine, _ = _engine()
    engine.send("play black D4")
    calls = []

    def fake_call_gnugo(sgf_file_name, cmd):
        with open(sgf_file_name) as f:
            calls.append((f.read(), cmd))
        return "B+7.5"

    monkeypatch.setattr(engine, "call_gnugo", fake_call_gnugo)
    assert engine.send(command) == _ok("B+7.5")
    [(sgf_text, sent)] = calls
    assert sent == gnugo_command
    assert ";B[" in sgf_text


@pytest.mark.parametrize("gnugo_fails", [False, True])
def test_scoring_does_not_leave_temp_files(monkeypatch, gnugo_fails):
    engine, _ = _engine()
    paths = []

    def fake_call_gnugo(path, cmd):
        paths.append(path)
        assert os.path.exists(path)  # still there while gnugo reads it
        if gnugo_fails:
            raise RuntimeError("gnugo crashed")
        return ""

    monkeypatch.setattr(engine, "call_gnugo", fake_call_gnugo)
    if gnugo_fails:
        with pytest.raises(RuntimeError):
            engine.send("final_score")
    else:
        engine.send("final_score")
    [path] = paths
    assert not os.path.exists(path)


def test_run_gnugo_without_gnugo_returns_nothing(tmp_path):
    assert gtp_wrapper.run_gnugo(str(tmp_path / "g.sgf"), "final_score\n") == ""


# --- run_gtp loop ----------------------------------------------------------------------

def test_run_gtp_answers_each_command_until_quit(capsys):
    lines = iter(["1 name\n2 boardsize 9\n3 play black C3", "4 genmove white", "5 quit",
                  "never read"])
    run_gtp(ScriptedPlayer([(6, 6)]), inpt_fn=lambda: next(lines), name="Loop", version="3")
    out, err = capsys.readouterr()
    assert out == "=1 Loop\n\n=2\n\n=3\n\n=4 G3\n\n=5\n\n"
    assert "GTP engine ready" in err
    assert next(lines) == "never read"


# --- the player's own move count ------------------------------------------------------

def test_own_moves_counts_genmoves_per_color():
    player = ScriptedPlayer()
    engine, _ = _engine(player)
    for command in ["genmove black", "genmove white", "genmove black", "genmove black"]:
        engine.send(command)
    assert player.own_moves == [0, 0, 1, 2]


def test_own_moves_ignores_handicap_sent_as_plain_moves():
    player = ScriptedPlayer()
    engine, _ = _engine(player)
    for vertex in ["D4", "Q16", "D16", "Q4"]:
        engine.send("play black {}".format(vertex))
    engine.send("play white K10")
    engine.send("genmove black")
    assert player.own_moves == [0]


@pytest.mark.parametrize("command", ["clear_board", "boardsize 19"])
def test_own_moves_resets_with_the_board(command):
    player = ScriptedPlayer()
    engine, _ = _engine(player)
    engine.send("genmove black")
    engine.send(command)
    engine.send("genmove black")
    assert player.own_moves == [0, 0]
