"""Assemble a self-contained folder for running the bot on a CPU-only Ubuntu server:
go_server.py (holds the network) + go_client.py (the GTP engine kgsGtp starts), with
only the code, model and locked dependencies they need.

    python deploy/build_deploy.py                    # b20c256 -> dist/neuralz-bot/
    python deploy/build_deploy.py --model b15c192latest --out dist/bot-b15

Runs with any Python 3 (standard library only) plus `uv` on PATH, which writes the
folder's uv.lock. Copy the result to the server and run its install.sh - see the
README.md it contains (from deploy/templates/README.md).
"""
import argparse
import datetime
import glob
import os
import shutil
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES = os.path.join(REPO, "deploy", "templates")

# Everything go_server.py and go_client.py import, plus the engine build script. The
# Cython engine ships as source (.pyx/.pxd): install.sh compiles it on the server.
ENGINE_MODULES = ["constants", "coordinates", "game_state", "group_logic", "ladders", "zobrist"]
RUNTIME_FILES = [
    "go_server.py",
    "go_client.py",
    "setup_cython.py",
    "AlphaGo/__init__.py",
    "AlphaGo/ai.py",
    "AlphaGo/util.py",
    "AlphaGo/go/__init__.py",
    *["AlphaGo/go/{}.{}".format(m, ext) for m in ENGINE_MODULES for ext in ("pyx", "pxd")],
    "AlphaGo/preprocessing/__init__.py",
    "AlphaGo/preprocessing/preprocessing.pyx",
    "AlphaGo/preprocessing/preprocessing.pxd",
    "AlphaGo/models/__init__.py",
    "AlphaGo/models/nn_util.py",
    "AlphaGo/models/policy.py",
    "AlphaGo/training/__init__.py",
    "AlphaGo/training/shard_stream.py",
    "interface/__init__.py",
    "interface/gtp_wrapper.py",
    "interface/katago_scorer.py",
]
TEMPLATE_FILES = ["README.md", "install.sh", "check_deploy.py", "start_server.sh",
                  "start_client.sh", "katago_analysis.cfg"]
# KataGo for end-of-game judging (go_server --katago): its Linux CPU (Eigen) binary and a
# small network, copied into the bundle's katago/ when present (git-ignored, like models)
KATAGO_DIR = os.path.join(REPO, "play_tests", "models", "katago")
EXECUTABLE = {"install.sh", "start_server.sh", "start_client.sh"}

# Runtime packages only, at the versions the repo's uv.lock uses (the trained models and
# tests were run with these). setuptools + cython build the engine; pygtp speaks GTP.
DEPENDENCIES = [
    "cython==3.3.0",
    "h5py==3.14.0",
    "keras==3.15.1",
    "numpy==2.5.3",
    "pygtp==0.3",
    "setuptools==84.0.0",
    "sgf==0.5",
    "tensorflow==2.21.0",
]

PYPROJECT = """\
# Generated by deploy/build_deploy.py - edit DEPENDENCIES there, not this file.
[project]
name = "neuralz-bot"
version = "0.1.0"
requires-python = ">=3.13,<3.14"
dependencies = [
{deps}
]

[tool.uv]
# Not an installable package: uv sync only creates .venv with the dependencies.
package = false
# Lock for the target server only (Ubuntu, x86-64), so the lock stays small and uv
# never has to resolve Windows/macOS wheels it will not use.
environments = ["sys_platform == 'linux' and platform_machine == 'x86_64'"]
"""


def fail(msg):
    sys.exit("build_deploy: " + msg)


def find_model(name, weights):
    model_dir = os.path.join(REPO, "play_tests", "models", name)
    if not os.path.isdir(model_dir):
        fail("no model directory {}".format(model_dir))
    jsons = glob.glob(os.path.join(model_dir, "*.json"))
    jsons = [j for j in jsons if not os.path.basename(j).startswith("metadata")]
    if len(jsons) != 1:
        fail("expected one model .json in {}, found {}".format(model_dir, jsons))
    if weights:
        weights_path = os.path.join(model_dir, weights)
        if not os.path.isfile(weights_path):
            fail("no weights file {}".format(weights_path))
    else:
        found = glob.glob(os.path.join(model_dir, "*.weights.h5"))
        if len(found) != 1:
            fail("expected one .weights.h5 in {} (pick one with --weights), found {}".format(
                model_dir, [os.path.basename(f) for f in found]))
        weights_path = found[0]
    return jsons[0], weights_path


def git(*args):
    return subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True,
                          check=True).stdout.strip()


def version_text(model_name, model_json, weights_path):
    commit = git("rev-parse", "--short", "HEAD")
    changed = git("status", "--porcelain", "--", *RUNTIME_FILES).splitlines()
    lines = [
        "commit: {}{}".format(commit, " + uncommitted changes" if changed else ""),
        "built: {}".format(datetime.datetime.now().isoformat(timespec="seconds")),
        "model: {} ({}, {})".format(model_name, os.path.basename(model_json),
                                    os.path.basename(weights_path)),
    ]
    if changed:
        lines.append("uncommitted runtime files:")
        lines += ["  " + c for c in changed]
    return "\n".join(lines) + "\n"


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--model", default="b20c256",
                   help="Directory name under play_tests/models/. Default: b20c256")
    p.add_argument("--weights", default=None,
                   help="Weights file in that directory, if it holds more than one")
    p.add_argument("--katago-dir", default=KATAGO_DIR,
                   help="Folder with KataGo's Linux binary ('katago') and one network "
                        "(*.bin.gz / *.txt.gz) for end-of-game judging. Default: "
                        "play_tests/models/katago; built without KataGo if missing")
    p.add_argument("--out", default=os.path.join(REPO, "dist", "neuralz-bot"),
                   help="Output folder, replaced if it exists. Default: dist/neuralz-bot")
    args = p.parse_args()

    if not shutil.which("uv"):
        fail("uv not found on PATH - it writes the folder's uv.lock")
    model_json, weights_path = find_model(args.model, args.weights)

    out = os.path.abspath(args.out)
    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(out)

    for rel in RUNTIME_FILES:
        src = os.path.join(REPO, rel)
        if not os.path.isfile(src):
            fail("missing runtime file {}".format(rel))
        dst = os.path.join(out, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)

    os.makedirs(os.path.join(out, "models"))
    shutil.copy2(model_json, os.path.join(out, "models"))
    shutil.copy2(weights_path, os.path.join(out, "models"))

    katago_net = None
    katago_bin = os.path.join(args.katago_dir, "katago")
    nets = sorted(glob.glob(os.path.join(args.katago_dir, "*.bin.gz")) +
                  glob.glob(os.path.join(args.katago_dir, "*.txt.gz")))
    if os.path.isfile(katago_bin) and len(nets) == 1:
        os.makedirs(os.path.join(out, "katago"))
        shutil.copy2(katago_bin, os.path.join(out, "katago", "katago"))
        shutil.copy2(nets[0], os.path.join(out, "katago"))
        katago_net = os.path.basename(nets[0])
    else:
        print("build_deploy: WARNING - no KataGo binary + single network in {}: built without "
              "end-of-game judging (bots fall back to GNU Go)".format(args.katago_dir))

    subs = {"@MODEL_JSON@": "models/" + os.path.basename(model_json),
            "@WEIGHTS@": "models/" + os.path.basename(weights_path),
            "@KATAGO_MODEL@": "katago/" + katago_net if katago_net else ""}
    for name in TEMPLATE_FILES:
        with open(os.path.join(TEMPLATES, name), encoding="utf-8") as f:
            text = f.read()
        for key, value in subs.items():
            text = text.replace(key, value)
        dst = os.path.join(out, name)
        # LF line endings: these run on Linux even when built on Windows
        with open(dst, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        if name in EXECUTABLE:
            os.chmod(dst, 0o755)

    with open(os.path.join(out, "pyproject.toml"), "w", encoding="utf-8", newline="\n") as f:
        f.write(PYPROJECT.format(deps="\n".join('    "{}",'.format(d) for d in DEPENDENCIES)))
    with open(os.path.join(out, ".python-version"), "w", newline="\n") as f:
        f.write("3.13\n")
    with open(os.path.join(out, "VERSION"), "w", encoding="utf-8", newline="\n") as f:
        f.write(version_text(args.model, model_json, weights_path))
        f.write("katago: {}\n".format(katago_net or "none (GNU Go fallback only)"))

    print("locking dependencies...")
    subprocess.run(["uv", "lock", "--quiet"], cwd=out, check=True)

    print("built {}".format(out))
    with open(os.path.join(out, "VERSION"), encoding="utf-8") as f:
        print(f.read())


if __name__ == "__main__":
    main()
